Github message scheme created
fedora-infra/webhook-to-fedora-messaging-messages pull request #1
Opened 2024-06-04 10:07 UTC by brngylni

2024-06-06 09:01 UTC, abompard requested changes

2024-06-06 09:01 UTC, abompard commented on webhook_to_fedora_messaging_messages_messages/__init__.py
> +
If these are github-specific, they they should be in a file named `github_utils.py` for example.

2024-06-10 07:39 UTC, brngylni commented on webhook_to_fedora_messaging_messages_messages/base.py
> +            return self.body["thing"]["url"]
removed

2024-06-10 07:42 UTC, brngylni commented on webhook_to_fedora_messaging_messages_messages/messages.py
> +        return self.body['body']['sender']['login']
removed

2024-06-10 09:19 UTC, closed without merging